name: Bow-Trainer
version: 1.1
api-version: 1.21.4
main: me.aurniox.bowtrainer.BowTrainer
commands:
  startgame:
    description: Starts a game for the specified player
    usage: /startgame <player>
    permission: bowtrainer.startgame
  stopgame:
    description: Stops a game for the specified player
    usage: /stopgame <player>
    permission: bowtrainer.stopgame
  setradius:
    description: Set the radius that chicken spawn around the player
    usage: /setradius <number>
    permission: bowtrainer.setradius
  setloc:
    description: Set the location of the game/lobby
    usage: /setloc <location>
    permission: bowtrainer.setloc